version: '3'
services:
  web:
    image: nginx:latest
    container_name: nginx1
    ports:
    - "80:80"
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    - ./nginx/my_nodejs.conf:/etc/nginx/conf.d/my_nodejs.conf:ro
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  nodeserver:
        build:
            context: .
        container_name: nodeserver1    
        ports:
            - "3000:3000"   